version: '3.4'

services:
  netcoretestdocker:
    image: netcoretestdocker
    build:
      context: .
      dockerfile: NetcoreTestDocker/Dockerfile
    ports:
      - "5000:80"
    networks:
      - nginx-proxy
  webapplication1:
    image: webappapi
    build:
      context: .
      dockerfile: WebAppApi/Dockerfile
    ports:
      - "5001:80"
    networks:
      - nginx-proxy
  webapplication3:
    image: webappapi3
    build:
      context: .
      dockerfile: WebAppApi3/Dockerfile
    ports:
      - "5002:80"
    networks:
      - nginx-proxy
  myapp.reverseproxy:
    image: reverseproxy_test:latest
    depends_on:
      - netcoretestdocker
      - webapplication1
    ports:
      - "8080:8080"
    container_name: reverseproxy_test
    build:
      context: .
      dockerfile: Containers/proxy/Dockerfile
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy: